# Project information
site_name: Talkamatic Docs
site_url: https://talkamatic.github.io/
site_author: Team Talkamatic
site_description: >-
    Talkamatic Dialog Manager (TDM) is based on 100 years of research
    on human dialog. Explore how it can be used to empower natural
    conversations in chatbots, telephony systems, and any other kinds
    of dialog systems today.

# Copyright
copyright: Copyright &copy; 2008 - 2020 Talkamatic

# Configuration
theme:
  name: material
  custom_dir: theme-overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: talkamatic/logo
  favicon: favicon.png

extra_css:
  - stylesheets/extra.css

nav:
    - Getting started: index.md
    - The foundation:
        - Issue-based Dialogue Management: ibdm.md
        - Dialog formalism: formalism.md
    - For dialog designers:
        - Introduction: for-dialog-designers/index.md
        - Step-by-step tutorial: for-dialog-designers/tutorial.md
        - Examples: for-dialog-designers/examples.md
        - Using Rasa NLU: for-dialog-designers/rasa_nlu.md
    - API definitions:
        - Pipeline API: api-definitions/pipeline_api.md
        - Service API: api-definitions/service_api.md
        - NLU API: api-definitions/nlu_api.md
        - NLG API: api-definitions/nlg_api.md
        - Shared objects: api-definitions/shared_objects.md
    - Dialog Domain Description definitions:
        - Introduction: dialog-domain-description-definition/index.md
        - Grammar:
            - Introduction: dialog-domain-description-definition/grammar/grammar.md
            - Elements:
                - Action: dialog-domain-description-definition/grammar/elements/action.md
                - Answer: dialog-domain-description-definition/grammar/elements/answer.md
                - Greeting: dialog-domain-description-definition/grammar/elements/greeting.md
                - Individual: dialog-domain-description-definition/grammar/elements/individual.md
                - Preconfirm: dialog-domain-description-definition/grammar/elements/preconfirm.md
                - Question: dialog-domain-description-definition/grammar/elements/question.md
                - Report: dialog-domain-description-definition/grammar/elements/report.md
                - Validity: dialog-domain-description-definition/grammar/elements/validity.md
            - Children:
                - Item: dialog-domain-description-definition/grammar/children/item.md
                - One-of: dialog-domain-description-definition/grammar/children/one-of.md
                - Slot: dialog-domain-description-definition/grammar/children/slot.md
                - VP: dialog-domain-description-definition/grammar/children/vp.md
        - Service Interface:
            - Introduction: dialog-domain-description-definition/service_interface/service_interface.md
            - Elements:
                - Action: dialog-domain-description-definition/service_interface/elements/action.md
                - Entity Recognizer: dialog-domain-description-definition/service_interface/elements/entity_recognizer.md
                - Query: dialog-domain-description-definition/service_interface/elements/query.md
                - Validator: dialog-domain-description-definition/service_interface/elements/validator.md
            - Children:
                - Failure Reasons: dialog-domain-description-definition/service_interface/children/failure_reasons.md
                - Parameters: dialog-domain-description-definition/service_interface/children/parameters.md
                - Target: dialog-domain-description-definition/service_interface/children/target.md
        - Domain:
            - Introduction: dialog-domain-description-definition/domain/domain.md
            - Elements:
                - Goal: dialog-domain-description-definition/domain/elements/goal.md
                - Parameters: dialog-domain-description-definition/domain/elements/parameters.md
                - Plan: dialog-domain-description-definition/domain/children/plan.md
            - Plan Items:
                - Assume Issue: dialog-domain-description-definition/domain/children/assume_issue.md
                - Assume Shared: dialog-domain-description-definition/domain/children/assume_shared.md
                - Assume System Belief: dialog-domain-description-definition/domain/children/assume_system_belief.md
                - Bind: dialog-domain-description-definition/domain/children/bind.md
                - Findout: dialog-domain-description-definition/domain/children/findout.md
                - Forget All: dialog-domain-description-definition/domain/children/forget_all.md
                - Forget: dialog-domain-description-definition/domain/children/forget.md
                - Get Done: dialog-domain-description-definition/domain/children/get_done.md
                - If: dialog-domain-description-definition/domain/children/if.md
                - Inform: dialog-domain-description-definition/domain/children/inform.md
                - Invoke Service Action: dialog-domain-description-definition/domain/children/invoke_service_action.md
                - Invoke Service Query: dialog-domain-description-definition/domain/children/invoke_service_query.md
                - Jumpto: dialog-domain-description-definition/domain/children/jumpto.md
                - Log: dialog-domain-description-definition/domain/children/log.md
                - Raise: dialog-domain-description-definition/domain/children/raise.md
                - Signal_Action_Completion: dialog-domain-description-definition/domain/children/signal_action_completion.md
                - Signal_Action_Failure: dialog-domain-description-definition/domain/children/signal_action_failure.md
            - Children:
                - Ask Feature: dialog-domain-description-definition/domain/children/ask_feature.md
                - Background: dialog-domain-description-definition/domain/children/background.md
                - Downdate Condition: dialog-domain-description-definition/domain/children/downdate_condition.md
                - Has Value: dialog-domain-description-definition/domain/children/has_value.md
                - Is Shared Fact: dialog-domain-description-definition/domain/children/is_shared_fact.md
                - Postplan: dialog-domain-description-definition/domain/children/postplan.md
                - Preferred: dialog-domain-description-definition/domain/children/preferred.md
                - Proposition: dialog-domain-description-definition/domain/children/proposition.md
                - Superaction: dialog-domain-description-definition/domain/children/superaction.md
        - Ontology:
            - Introduction: dialog-domain-description-definition/ontology/ontology.md
            - Elements:
                - Sort: dialog-domain-description-definition/ontology/elements/sort.md
                - Predicate: dialog-domain-description-definition/ontology/elements/predicate.md
                - Individual: dialog-domain-description-definition/ontology/elements/individual.md
                - Action: dialog-domain-description-definition/ontology/elements/action.md

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  - minify:
      minify_html: true
